### ISSUE TITLE
Support for data provider names as is

### ISSUE THREAD

**Issue by zeleznypa** [sempro/phpunit-pretty-print#12]
PhpUnit [data provider support names](https://phpunit.de/manual/current/en/writing-tests-for-phpunit.html#writing-tests-for-phpunit.data-providers.examples.DataTest1.php) and will it be useful to show them as is :)

```php
    /**
     * Standard set of values for testing string supported values
     *
     * @return array[]
     */
    public static function stringDataProvider(): array
    {
        return [
            '[a-z] string' => ['string'],
            '[a-Z] string' => ['String'],
            '[a-Z0-9] string' => ['String1234'],
            'UTF-8 string' => ['ěščřžýáíéůúňťĚŠČŘŽÝÁÍÉŮÚŇŤ'],
            'Special characters string' => ['~*!-.:/\\"\''],
        ];
    }

    /**
     * @dataProvider stringDataProvider
     */
    public function testSuccess($foo): void
    {
        ...
    }
```

![dataprovider names](https://user-images.githubusercontent.com/1191472/37874613-8fd77338-3032-11e8-8581-4c42a0e62c0b.png)

**Comment by ecrmnn** [comment]
I'm sorry, but I don't understand what this does.

Could you give me a few examples?

**Comment by zeleznypa** [comment]
@ecrmnn When you try the example from the issue description, the expected result is:

```
✅ success [a-z] string [0.001s]
✅ success [a-Z] string [0.000s]
✅ success [a-Z0-9] string [0.000s]
✅ success UTF-8 string [0.000s]
✅ success Special characters string [0.000s]
```

But current implementation drop the names of data provider steps like in the attached screenshot

**Comment by hotmeteor** [comment]
Ya, this would be nice. Basically, the request is to append the key of the data provider values to the test name.

**Comment by ventrec** [comment]
We would accept a pull request that fixes this.

**Comment by bobbybouwmann** [comment]
@ventrec I created a PR to add this functionality ;)

**Comment by zeleznypa** [comment]
It work like a charm. Many thanks

**Comment by bobbybouwmann** [comment]
@zeleznypa Awesome! I'm very happy with the outcome as well!
