### ISSUE TITLE
1.0.3 requires PHP >= 7.0.0 but uses void return types

### ISSUE THREAD

**Issue by michaeldyrynda** [sempro/phpunit-pretty-print#19]
I'm not sure what the best course of action for the package is here.

1.0.3 introduced [`void` return types](https://github.com/sempro/phpunit-pretty-print/commit/214fe4e342f0402e642a8c24f04896b50aaa3700) but didn't update its PHP dependency to >=7.1.0, so this version of the package doesn't actually work with the requirement.

i.e. I have `config.platform.php = 7.0.30`, as my development environment is running PHP 7.1.20. As a result, `composer require sempro/phpunit-pretty-print` uses `~1.0` by default and installs 1.0.3 as I'm using `phpunit/phpunit=6.5.13`. This fails when we run the test suite in CI on 7.0.30.

**Comment by ventrec** [comment]
Are you able to update your phpunit version in order to use a newer version of the package? Would this solve your problem?

**Comment by michaeldyrynda** [comment]
Unfortunately not as we're still using 7.0.30 in production for this project. I don't think there's much that can be done as the release is already tagged? Just flagging it as problematic in case anybody else comes across this.
