### ISSUE TITLE
Instead of green checkmark I see Blocks

### ISSUE THREAD

**Issue by dschiller** [sempro/phpunit-pretty-print#20]
If I execute my Tests with ```vendor\bin\phpunit --printer Sempro\PHPUnitPrettyPrinter\PrettyPrinter tests\UnitTests\Controls``` I just see squared Blocks instead of Checkmarks and they are also white instead of green.
![Image 3](https://user-images.githubusercontent.com/3144986/54614020-000fe880-4a5c-11e9-8f7b-2e7540e357b3.png)

**Comment by ventrec** [comment]
What OS are you on? What shell are you using for your unix terminal?

The text is supposed to be green here, and it's all white on your screenshot.

**Comment by dschiller** [comment]
I am using Windows 10 and as Shell I use just Windows Command Line or so called ```Command Prompt```.

**Comment by ventrec** [comment]
This is just a wild guess but the issue might be that the `Command Prompt` doesn't support unicode or colors.

I'm not sure what terminal you should use on windows in order to get the most unix-like experience, but maybe something like https://cmder.net/ ?

**Comment by dschiller** [comment]
I see. Thank you *ventrec*.

**Comment by dschiller** [comment]
I tried Cmder. It's not green but the Unicode Chars seems to work.

![Image 3](https://user-images.githubusercontent.com/3144986/54620487-86c9c300-4a66-11e9-8bc8-35ce7661c172.png)

**Comment by dschiller** [comment]
Issue can be **closed**.

**Comment by pinaakimajumder** [comment]
Facing the same checkmark issue in Windows 7 64bit command prompt/terminal.

![cmd-checkmark-issue](https://user-images.githubusercontent.com/79135437/126433436-7495e78b-8bf5-4244-ac34-8e5d4127ae30.jpg)

Thank you @ventrec, checkmark is showing in Cmder.

![cmder](https://user-images.githubusercontent.com/79135437/126433649-eb4f1d1b-83ba-4c8f-b458-680f179f06d4.jpg)
