### ISSUE TITLE
[Feature Request] Display progress during output

### ISSUE THREAD

**Issue by viktorivanov** [sempro/phpunit-pretty-print#25]
Hi, I find your package very useful when running big test suites where I can easily see any failing assertions right away without the need for the whole process to finish.

I have a feature request: Can you add a few extra lines in order to include the progress describing the current progress? Something like `current/total` at the beginning of every line.

Example:
![](https://d.pr/i/t64BYz+)

I can make a PR request for that if you think it's worth it and others might find it useful as well.

Thanks in advance.

**Comment by ventrec** [comment]
Hi @viktorivanov, and thanks for your input.

Ideally something like this would consist of a progress bar that would be constantly present at the bottom while running tests. 

Whatever the solution is, this should be optional and controlled by a config value in phpunit.xml.

Feel free to submit a PR with the changes, relevant tests and updated readme specifying how to activate the progress indicator.

**Comment by viktorivanov** [comment]
Thank you @ventrec 

> Ideally something like this would consist of a progress bar that would be constantly present at the bottom while running tests.

I am not sure if this is possible unless some third party software is involved.


> Whatever the solution is, this should be optional and controlled by a config value in phpunit.xml.

I don't think PHPUnit supports custom configuration attributes, but I can use the following line inside the phpunit.xml file to set a php environment variable:
```
<env name="PRETTY_PRINT_PROGRESS" value="true" />
``` 

Here is a screenshot of the progress bar in action
![](https://d.pr/i/wdPjKA+)

**Comment by ventrec** [comment]
That sounds good.

Make sure that the progress bar is disabled by default, and prefix the env name with `PHPUNIT_` in order to avoid potential conflicts for users.
