### ISSUE TITLE
PhpUnit 8.3 deprecation notice

### ISSUE THREAD

**Issue by robbah** [sempro/phpunit-pretty-print#28]
I am receiving this deprecation notice when running on PhpUnit 8.3.5

` The "PHPUnit\TextUI\ResultPrinter" class is considered internal This class is not covered by the backward compatibility promise for PHPUnit. It may change without further notice. You should not use it from "Sempro\PHPUnitPrettyPrinter\PrettyPrinter"`

**Comment by AdamKyle** [comment]
It sounds like you should replace the class with phpunit's - in other words, sounds like this package is now internal in their own implementation. I could be wrong.

**Comment by ecrmnn** [comment]
Apparently `PHPUnit\TextUI\ResultPrinter` is `@internal` in version 8. I'm not experiencing this when using PHPUnit 7. Not sure how to fix this yet.

Seems like other printers have this too.
https://github.com/mikeerickson/phpunit-pretty-result-printer/issues/155

**Comment by parkourben99** [comment]
It looks like they have replaced this class with a interface in phpunit 9.
