### ISSUE TITLE
[Feature Request] Colorize time on slow tests

### ISSUE THREAD

**Issue by antonkomarev** [sempro/phpunit-pretty-print#3]
I found it useful to see highlighted test execution time in case when test is too slow. I saw this in another package:
https://github.com/LimeDeck/phpunit-detailed-printer/blob/d9ac901fab9a530da6728190469e683c2e452778/src/Printer.php#L189-L203

**Comment by ecrmnn** [comment]
Hi @a-komarev.
Thanks for all your contributions! 👍
