### ISSUE TITLE
PHP Unit 9 error PHPUnitPrettyPrinter\PrettyPrinter cannot extend from interface

### ISSUE THREAD

**Issue by juhasev** [sempro/phpunit-pretty-print#31]
Getting this when attempting to use the plugin with PHPUnit 9. Reverting back to 8.5 resolved this issue.

PHP Fatal error:  Class Sempro\PHPUnitPrettyPrinter\PrettyPrinter cannot extend from interface PHPUnit\TextUI\ResultPrinter in /code/vendor/sempro/phpunit-pretty-print/src/PrettyPrinter.php on line 13

**Comment by ecrmnn** [comment]
Currently not working with PHPUnit 9
