### ISSUE TITLE
Doesn't work with PHPUnit 9

### ISSUE THREAD

**Issue by MLDMoritz** [sempro/phpunit-pretty-print#32]
As #28 is not resolved this now doesn't work with PHPUnit 9.

We should fix it or limit the version constraint.

**Comment by cedrichennequin** [comment]
Hi,

In version 9 of PHPUnit, the printer needs to inherit from the class `DefaultResultPrinter` (the namespace is `PHPUnit\TextUI\DefaultResultPrinter`).
In this version the code is :
```PHP
class PrettyPrinter extends ResultPrinter implements TestListener {}
```
And can be replaced by :
```PHP
class PrettyPrinter extends DefaultResultPrinter {}
```
I don't know if the implementation change with version 9 and the documentation can be found [here](https://api.phpunit.de/classes/PHPUnit_TextUI_DefaultResultPrinter.html).

**Comment by niquenen** [comment]
Hi,

In version 9 of PHPUnit, the printer needs to inherit from the class `DefaultResultPrinter` (the namespace is `PHPUnit\TextUI\DefaultResultPrinter`).
In this version the code is :
```PHP
class PrettyPrinter extends ResultPrinter implements TestListener {}
```
And can be replaced by :
```PHP
class PrettyPrinter extends DefaultResultPrinter {}
```
I don't know if the implementation change with version 9 and the documentation can be found [here](https://api.phpunit.de/classes/PHPUnit_TextUI_DefaultResultPrinter.html).

**Comment by ventrec** [comment]
The latest release should work with PHPUnit 9.

**Comment by piRGoif** [comment]
Hello,

I see in this repo that the fix was implemented (https://github.com/indentno/phpunit-pretty-print/blob/develop/src/PrettyPrinter.php)
But the latest package available on packagist.org is 1.4.0 and is still incompatible with PHPUnit 9 (same error). I see in its source it doesn't contains the fix.
There are also no new release on this repository...

Can a new PHPUnit 9 compatible release be made please ?

**Comment by ventrec** [comment]
> Hello,
> 
> I see in this repo that the fix was implemented (https://github.com/indentno/phpunit-pretty-print/blob/develop/src/PrettyPrinter.php) But the latest package available on packagist.org is 1.4.0 and is still incompatible with PHPUnit 9 (same error). I see in its source it doesn't contains the fix. There are also no new release on this repository...
> 
> Can a new PHPUnit 9 compatible release be made please ?

Are you using the correct PrettyPrinter class? (The readme specifies that you should use the \Sempro\PHPUnitPrettyPrinter\PrettyPrinterForPhpUnit9 class for PHPUnit 9)

**Comment by piRGoif** [comment]
All my apologies, indeed it was well written in the README.md included in the package... but I missed it :/

In the phpunit XML config I changed the `printerClass` from `Sempro\PHPUnitPrettyPrinter\PrettyPrinter` to `\Sempro\PHPUnitPrettyPrinter\PrettyPrinterForPhpUnit9` and now everything is OK 🥳

You can close this ticket again, sorry for the waste of time and many thanks for your quick answer ! (and by the way for this fantastic piece of code !!)

For future people like me, the information is now in this ticket O:)
But may I suggest also adding a PHPDoc block comment for the PrettyPrinter class, something like : 

```php
/**
 * For PHPUnit9 you must use instead {@see PrettyPrinterForPhpUnit9}
 *
 * @deprecated 1.4.0
 *
 * @link https://github.com/indentno/phpunit-pretty-print/issues/32 Fix for PHPUnit9 compatibility
 */
```

**Comment by ventrec** [comment]
> All my apologies, indeed it was well written in the README.md included in the package... but I missed it :/
> 
> In the phpunit XML config I changed the `printerClass` from `Sempro\PHPUnitPrettyPrinter\PrettyPrinter` to `\Sempro\PHPUnitPrettyPrinter\PrettyPrinterForPhpUnit9` and now everything is OK 🥳
> 
> You can close this ticket again, sorry for the waste of time and many thanks for your quick answer ! (and by the way for this fantastic piece of code !!)
> 
> For future people like me, the information is now in this ticket O:) But may I suggest also adding a PHPDoc block comment for the PrettyPrinter class, something like :
> 
> ```
> /**
>  * For PHPUnit9 you must use instead {@see PrettyPrinterForPhpUnit9}
>  *
>  * @deprecated 1.4.0
>  *
>  * @link https://github.com/indentno/phpunit-pretty-print/issues/32 Fix for PHPUnit9 compatibility
>  */
> ```

No worries. Thank you for the kind words 🙂

Feel free to send in a Pull Request with the changes you suggested!
