### ISSUE TITLE
Invalid phpunit range in composer.json

### ISSUE THREAD

**Issue by martindanielsson** [sempro/phpunit-pretty-print#41]
This package composer.json states: `"phpunit/phpunit": ">=7.0.0 ^9.0.0"` but this is not a valid range, it is the equivalent of just having `^9.0.0` so it's not installable if you have phpunit 8.5 required in your main composer.

Valid range would be: `>=7.0.0 <10.0.0`, if that's what you're going for!

Info taken from: https://getcomposer.org/doc/articles/versions.md#version-range 

> By using comparison operators you can specify ranges of valid versions. Valid operators are `>, >=, <, <=, !=`.

Composer 1:
```
  Problem 1
    - Installation request for sempro/phpunit-pretty-print ^1.3 -> satisfiable by sempro/phpunit-pretty-print[1.3.0].
    - sempro/phpunit-pretty-print 1.3.0 requires phpunit/phpunit >=7.0.0 ^9.0.0 -> satisfiable by phpunit/phpunit[9.0.0, 9.0.1, 9.0.2, 9.1.0, 9.1.1, 9.1.2, 9.1.3, 9.1.4, 9.1.5, 9.2.0, 9.2.1, 9.2.2, 9.2.3, 9.2.4, 9.2.5, 9.2.6, 9.3.0, 9.3.1, 9.3.10, 9.3.11, 9.3.2, 9.3.3, 9.3.4, 9.3.5, 9.3.6, 9.3.7, 9.3.8, 9.3.9, 9.4.0, 9.4.1, 9.4.2, 9.4.x-dev, 9.5.x-dev] but these conflict with your requirements or minimum-stability.
```

Composer 2:
```
  Problem 1
    - Root composer.json requires sempro/phpunit-pretty-print ^1.3 -> satisfiable by sempro/phpunit-pretty-print[1.3.0].
    - sempro/phpunit-pretty-print 1.3.0 requires phpunit/phpunit >=7.0.0 ^9.0.0 -> found phpunit/phpunit[9.0.0, ..., 9.4.2] but it conflicts with your root composer.json require (^8.5).
```

**Comment by ventrec** [comment]
This should be fixed in the latest release.
